"""empty message

Revision ID: 10f5095e08e
Revises: 39478f6ab9b
Create Date: 2015-01-27 04:08:58.227791

"""

# revision identifiers, used by Alembic.
revision = '10f5095e08e'
down_revision = '39478f6ab9b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
