"""empty message

Revision ID: 14a83cff835
Revises: 4e36b0b8a23
Create Date: 2015-02-08 21:38:16.078196

"""

# revision identifiers, used by Alembic.
revision = '14a83cff835'
down_revision = '4e36b0b8a23'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_image', sa.String(length=255), nullable=True),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('color', sa.String(length=255), nullable=True),
    sa.Column('material_top', sa.String(length=255), nullable=True),
    sa.Column('lining', sa.String(length=255), nullable=True),
    sa.Column('analpa_size', sa.String(length=255), nullable=True),
    sa.Column('insole', sa.String(length=255), nullable=True),
    sa.Column('segment', sa.String(length=255), nullable=True),
    sa.Column('season', sa.String(length=255), nullable=True),
    sa.Column('mark', sa.String(length=255), nullable=True),
    sa.Column('item_type', sa.String(length=255), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('group_catalog_id', sa.Integer(), nullable=True),
    sa.Column('coll_status', sa.Integer(), nullable=True),
    sa.Column('image_2', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['group_catalog_id'], ['group_catalog_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('catalog_item')
    ### end Alembic commands ###
