"""empty message

Revision ID: 181233eb63e
Revises: 47f32b7dd0c
Create Date: 2015-02-05 10:53:22.183366

"""

# revision identifiers, used by Alembic.
revision = '181233eb63e'
down_revision = '47f32b7dd0c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('map_item')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map_item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('position', sa.VARCHAR(), nullable=True),
    sa.Column('city_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
