"""empty message

Revision ID: 188e7d87a0f
Revises: 23316676812
Create Date: 2015-02-17 21:51:00.538767

"""

# revision identifiers, used by Alembic.
revision = '188e7d87a0f'
down_revision = '23316676812'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_rating',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('voters', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_rating')
    ### end Alembic commands ###
