"""empty message

Revision ID: 1a6f67bcc88
Revises: 2db9943eafb
Create Date: 2015-02-24 03:08:11.388099

"""

# revision identifiers, used by Alembic.
revision = '1a6f67bcc88'
down_revision = '2db9943eafb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('side_catalog_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    #op.create_foreign_key(None, 'blog_page_item', 'blog_category', ['category_id'], ['id'])
    #op.create_foreign_key(None, 'item_rating', 'catalog_item', ['id'], ['sku'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item_rating', type_='foreignkey')
    op.drop_constraint(None, 'blog_page_item', type_='foreignkey')
    op.drop_table('side_catalog_group')
    ### end Alembic commands ###
