"""empty message

Revision ID: 1c8d302bd62
Revises: 31c349b32d4
Create Date: 2015-01-02 20:29:48.774265

"""

# revision identifiers, used by Alembic.
revision = '1c8d302bd62'
down_revision = '31c349b32d4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('map_item')
    ### end Alembic commands ###
