"""empty message

Revision ID: 1d618c673
Revises: 21d676bcda8
Create Date: 2015-01-19 21:29:38.961453

"""

# revision identifiers, used by Alembic.
revision = '1d618c673'
down_revision = '21d676bcda8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
