"""empty message

Revision ID: 213432d21e2
Revises: 34b4534139e
Create Date: 2015-02-24 05:23:53.340284

"""

# revision identifiers, used by Alembic.
revision = '213432d21e2'
down_revision = '34b4534139e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    pass
    ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('item_rating')
    ### end Alembic commands ###


def downgrade():
    pass
    ### commands auto generated by Alembic - please adjust! ###
    #op.create_table('item_rating',
    #sa.Column('id', sa.VARCHAR(), nullable=False),
    #sa.Column('voters', sa.INTEGER(), nullable=True),
    #sa.Column('rating', sa.INTEGER(), nullable=True),
    #sa.PrimaryKeyConstraint('id')
    #)
    ### end Alembic commands ###
