"""empty message

Revision ID: 21d676bcda8
Revises: d38746174e
Create Date: 2015-01-19 21:24:42.755560

"""

# revision identifiers, used by Alembic.
revision = '21d676bcda8'
down_revision = 'd38746174e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    pass
    ### commands auto generated by Alembic - please adjust! ###
    #op.create_foreign_key(None, 'user_item', 'group_item', ['role_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    pass
    ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint(None, 'user_item', type_='foreignkey')
    ### end Alembic commands ###
