"""empty message

Revision ID: 23316676812
Revises: e6763be675
Create Date: 2015-02-17 20:48:54.250720

"""

# revision identifiers, used by Alembic.
revision = '23316676812'
down_revision = 'e6763be675'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribed_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('birthday', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscribed_users')
    ### end Alembic commands ###
