"""empty message

Revision ID: 26b1c24cddb
Revises: 10f5095e08e
Create Date: 2015-01-27 04:09:04.415983

"""

# revision identifiers, used by Alembic.
revision = '26b1c24cddb'
down_revision = '10f5095e08e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
