"""empty message

Revision ID: 2c0e7be024a
Revises: 2ee63140fce
Create Date: 2014-12-15 15:08:29.635600

"""

# revision identifiers, used by Alembic.
revision = '2c0e7be024a'
down_revision = '2ee63140fce'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_item', sa.Column('session_key', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_item', 'session_key')
    ### end Alembic commands ###
