"""empty message

Revision ID: 2db9943eafb
Revises: 50d5f778409
Create Date: 2015-02-24 01:52:06.655984

"""

# revision identifiers, used by Alembic.
revision = '2db9943eafb'
down_revision = '50d5f778409'

from alembic import op
import sqlalchemy as sa


def upgrade():
    pass
    ### commands auto generated by Alembic - please adjust! ###
    #op.create_foreign_key(None, 'blog_page_item', 'blog_category', ['category_id'], ['id'])
    #op.create_foreign_key(None, 'item_rating', 'catalog_item', ['id'], ['sku'])
    ### end Alembic commands ###


def downgrade():
    pass
    ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint(None, 'item_rating', type_='foreignkey')
    #op.drop_constraint(None, 'blog_page_item', type_='foreignkey')
    ### end Alembic commands ###
