"""empty message

Revision ID: 3153bc18bc7
Revises: c12eaccb31
Create Date: 2015-03-05 05:41:00.937352

"""

# revision identifiers, used by Alembic.
revision = '3153bc18bc7'
down_revision = 'c12eaccb31'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('side_catalog_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entiny_type_id', sa.Integer(), nullable=True),
    sa.Column('attribute_code', sa.String(), nullable=True),
    sa.Column('frontend_label', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('side_catalog_properties',
    sa.Column('value_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('attribute_id', sa.Integer(), nullable=True),
    sa.Column('attribute_code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('value_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('side_catalog_properties')
    op.drop_table('side_catalog_attributes')
    ### end Alembic commands ###
