"""empty message

Revision ID: 31c349b32d4
Revises: 1e94213f538
Create Date: 2015-01-02 20:29:14.534909

"""

# revision identifiers, used by Alembic.
revision = '31c349b32d4'
down_revision = '1e94213f538'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('map_item')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map_item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('position_x', sa.FLOAT(), nullable=True),
    sa.Column('position_y', sa.FLOAT(), nullable=True),
    sa.Column('position', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
