"""empty message

Revision ID: 335a27f45cf
Revises: 1a6f67bcc88
Create Date: 2015-02-24 05:14:33.779419

"""

# revision identifiers, used by Alembic.
revision = '335a27f45cf'
down_revision = '1a6f67bcc88'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('side_catalog_group')
    #op.create_foreign_key(None, 'blog_page_item', 'blog_category', ['category_id'], ['id'])
    #op.create_foreign_key(None, 'item_rating', 'catalog_item', ['id'], ['sku'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint(None, 'item_rating', type_='foreignkey')
    #op.drop_constraint(None, 'blog_page_item', type_='foreignkey')
    op.create_table('side_catalog_group',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('parent_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
