"""empty message

Revision ID: 3408b486c4b
Revises: 4a67bfcc1e7
Create Date: 2015-01-09 21:13:39.402002

"""

# revision identifiers, used by Alembic.
revision = '3408b486c4b'
down_revision = '4a67bfcc1e7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('view_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('method', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_rights',
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('view_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group_item.id'], ),
    sa.ForeignKeyConstraint(['view_name'], ['view_item.name'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_rights')
    op.drop_table('view_item')
    ### end Alembic commands ###
