"""empty message

Revision ID: 34b4534139e
Revises: 335a27f45cf
Create Date: 2015-02-24 05:15:14.320838

"""

# revision identifiers, used by Alembic.
revision = '34b4534139e'
down_revision = '335a27f45cf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('side_catalog_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('active', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    #op.create_foreign_key(None, 'blog_page_item', 'blog_category', ['category_id'], ['id'])
    #op.create_foreign_key(None, 'item_rating', 'catalog_item', ['id'], ['sku'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint(None, 'item_rating', type_='foreignkey')
    #op.drop_constraint(None, 'blog_page_item', type_='foreignkey')
    op.drop_table('side_catalog_group')
    ### end Alembic commands ###
