"""empty message

Revision ID: 39478f6ab9b
Revises: 1dbda373f3f
Create Date: 2015-01-27 04:08:45.603029

"""

# revision identifiers, used by Alembic.
revision = '39478f6ab9b'
down_revision = '1dbda373f3f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
