"""empty message

Revision ID: 3a50769880b
Revises: 1c8d302bd62
Create Date: 2015-01-02 23:01:17.464897

"""

# revision identifiers, used by Alembic.
revision = '3a50769880b'
down_revision = '1c8d302bd62'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('city_item')
    ### end Alembic commands ###
