"""empty message

Revision ID: 3cc336a09d8
Revises: 3153bc18bc7
Create Date: 2015-03-05 06:06:14.464033

"""

# revision identifiers, used by Alembic.
revision = '3cc336a09d8'
down_revision = '3153bc18bc7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('side_catalog_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type_id', sa.Integer(), nullable=True),
    sa.Column('attribute_code', sa.String(), nullable=True),
    sa.Column('frontend_label', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('side_catalog_attributes')
    ### end Alembic commands ###
