"""empty message

Revision ID: 4235dc115a5
Revises: 3408b486c4b
Create Date: 2015-01-09 21:22:08.433087

"""

# revision identifiers, used by Alembic.
revision = '4235dc115a5'
down_revision = '3408b486c4b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_rights')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_rights',
    sa.Column('group_id', sa.INTEGER(), nullable=True),
    sa.Column('view_name', sa.VARCHAR(), nullable=True),
    sa.Column('view_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group_item.id'], ),
    sa.ForeignKeyConstraint(['view_name'], ['view_item.name'], )
    )
    ### end Alembic commands ###
