"""empty message

Revision ID: 434ad27f083
Revises: c0e7a753f3
Create Date: 2015-01-09 21:06:43.775218

"""

# revision identifiers, used by Alembic.
revision = '434ad27f083'
down_revision = 'c0e7a753f3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_rights')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_rights',
    sa.Column('group_id', sa.INTEGER(), nullable=True),
    sa.Column('view_name', sa.VARCHAR(), nullable=True),
    sa.Column('access', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group_item.id'], ),
    sa.ForeignKeyConstraint(['view_name'], ['view_item.name'], )
    )
    ### end Alembic commands ###
