"""empty message

Revision ID: 45a96d70d76
Revises: 4235dc115a5
Create Date: 2015-01-09 21:22:20.294593

"""

# revision identifiers, used by Alembic.
revision = '45a96d70d76'
down_revision = '4235dc115a5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_rights',
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('view_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group_item.id'], ),
    sa.ForeignKeyConstraint(['view_id'], ['view_item.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_rights')
    ### end Alembic commands ###
