"""empty message

Revision ID: 48cdece394a
Revises: 26b1c24cddb
Create Date: 2015-01-28 04:57:53.408705

"""

# revision identifiers, used by Alembic.
revision = '48cdece394a'
down_revision = '26b1c24cddb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_item', sa.Column('coll_status', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catalog_item', 'coll_status')
    ### end Alembic commands ###
