"""empty message

Revision ID: 49bf4cc66c3
Revises: 188e7d87a0f
Create Date: 2015-02-23 02:08:55.824153

"""

# revision identifiers, used by Alembic.
revision = '49bf4cc66c3'
down_revision = '188e7d87a0f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    pass
    ### commands auto generated by Alembic - please adjust! ###
    #op.create_table('side_catalog_item',
    #sa.Column('id', sa.Integer(), nullable=False),
    #sa.Column('sku', sa.String(), nullable=True),
    #sa.Column('data', sa.String(), nullable=True),
    #sa.PrimaryKeyConstraint('id')
    #)
    #op.create_foreign_key(None, 'item_rating', 'catalog_item', ['id'], ['sku'])
    ### end Alembic commands ###


def downgrade():
    pass
    ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint(None, 'item_rating', type_='foreignkey')
    #op.drop_table('side_catalog_item')
    ### end Alembic commands ###
