"""empty message

Revision ID: 4a67bfcc1e7
Revises: 434ad27f083
Create Date: 2015-01-09 21:12:48.789762

"""

# revision identifiers, used by Alembic.
revision = '4a67bfcc1e7'
down_revision = '434ad27f083'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('view_item')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('view_item',
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    ### end Alembic commands ###
