"""empty message

Revision ID: 4e36b0b8a23
Revises: deb4de7e9
Create Date: 2015-02-08 21:37:56.705594

"""

# revision identifiers, used by Alembic.
revision = '4e36b0b8a23'
down_revision = 'deb4de7e9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('catalog_item')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('base_image', sa.VARCHAR(length=255), nullable=True),
    sa.Column('sku', sa.VARCHAR(length=255), nullable=True),
    sa.Column('color', sa.VARCHAR(length=255), nullable=True),
    sa.Column('material_top', sa.VARCHAR(length=255), nullable=True),
    sa.Column('lining', sa.VARCHAR(length=255), nullable=True),
    sa.Column('analpa_size', sa.VARCHAR(length=255), nullable=True),
    sa.Column('insole', sa.VARCHAR(length=255), nullable=True),
    sa.Column('segment', sa.VARCHAR(length=255), nullable=True),
    sa.Column('season', sa.VARCHAR(length=255), nullable=True),
    sa.Column('year', sa.VARCHAR(length=255), nullable=True),
    sa.Column('mark', sa.VARCHAR(length=255), nullable=True),
    sa.Column('item_type', sa.VARCHAR(length=255), nullable=True),
    sa.Column('status', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_time', sa.DATETIME(), nullable=True),
    sa.Column('group_catalog_id', sa.INTEGER(), nullable=True),
    sa.Column('coll_status', sa.INTEGER(), nullable=True),
    sa.Column('image_2', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['group_catalog_id'], ['group_catalog_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
