"""empty message

Revision ID: 50d5f778409
Revises: 50e29c7d1c8
Create Date: 2015-02-23 06:19:50.317299

"""

# revision identifiers, used by Alembic.
revision = '50d5f778409'
down_revision = '50e29c7d1c8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_block_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('data', sa.String(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['blog_block_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blog_page_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('meta', sa.String(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['blog_category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('blog_page_blocks',
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('block_id', sa.Integer(), nullable=True),
    sa.Column('place', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['blog_block_item.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['blog_page_item.id'], )
    )
    #op.create_foreign_key(None, 'item_rating', 'catalog_item', ['id'], ['sku'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint(None, 'item_rating', type_='foreignkey')
    op.drop_table('blog_page_blocks')
    op.drop_table('blog_page_item')
    op.drop_table('blog_block_item')
    ### end Alembic commands ###
