"""empty message

Revision ID: 50e29c7d1c8
Revises: 58581b08733
Create Date: 2015-02-23 05:42:25.592843

"""

# revision identifiers, used by Alembic.
revision = '50e29c7d1c8'
down_revision = '58581b08733'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    #op.create_foreign_key(None, 'item_rating', 'catalog_item', ['id'], ['sku'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint(None, 'item_rating', type_='foreignkey')
    op.drop_table('blog_category')
    ### end Alembic commands ###
