"""empty message

Revision ID: 58581b08733
Revises: 49bf4cc66c3
Create Date: 2015-02-23 02:51:30.202543

"""

# revision identifiers, used by Alembic.
revision = '58581b08733'
down_revision = '49bf4cc66c3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    pass
    ### commands auto generated by Alembic - please adjust! ###
    #op.create_table('side_catalog_item_image',
    #sa.Column('id', sa.Integer(), nullable=False),
    #sa.Column('item_id', sa.Integer(), nullable=True),
    #sa.Column('url', sa.String(), nullable=True),
    #sa.ForeignKeyConstraint(['item_id'], ['side_catalog_item.id'], ),
    #sa.PrimaryKeyConstraint('id')
    #)
    #op.create_foreign_key(None, 'item_rating', 'catalog_item', ['id'], ['sku'])
    ### end Alembic commands ###


def downgrade():
    pass
    ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint(None, 'item_rating', type_='foreignkey')
    #op.drop_table('side_catalog_item_image')
    ### end Alembic commands ###
