"""empty message

Revision ID: c0e7a753f3
Revises: 37830685bc8
Create Date: 2015-01-09 20:02:20.778256

"""

# revision identifiers, used by Alembic.
revision = 'c0e7a753f3'
down_revision = '37830685bc8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_rights', sa.Column('access', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_rights', 'access')
    ### end Alembic commands ###
