"""empty message

Revision ID: c12eaccb31
Revises: 213432d21e2
Create Date: 2015-02-24 05:25:44.194529

"""

# revision identifiers, used by Alembic.
revision = 'c12eaccb31'
down_revision = '213432d21e2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_rating',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('voters', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['side_catalog_item.sku'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_rating')
    ### end Alembic commands ###
