"""empty message

Revision ID: d7f7536a65
Revises: 360a93099f6
Create Date: 2014-12-12 05:24:26.678601

"""

# revision identifiers, used by Alembic.
revision = 'd7f7536a65'
down_revision = '360a93099f6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('block_item', sa.Column('order', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('block_item', 'order')
    ### end Alembic commands ###
