"""empty message

Revision ID: e6763be675
Revises: 14a83cff835
Create Date: 2015-02-08 21:59:50.374876

"""

# revision identifiers, used by Alembic.
revision = 'e6763be675'
down_revision = '14a83cff835'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_item', sa.Column('image_3', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catalog_item', 'image_3')
    ### end Alembic commands ###
